language: bash
sudo: required
env:
  global:

branches:
  only:
  - master

services:
- docker

before_script: 

script:
- bash ./unifi/mock_test.sh
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=$DOCKER_USER/ubiquiti-docker
- make -C unifi build
- if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then make -C unifi release; fi
after_success: 
