language: bash
sudo: required
env:
  global:
    DOCKER_EMAIL:
      secure: DMRfRhjY69QWJeBY6FrRXOQojAFVkxWBCKYyepqEui8gilYWtNheZq+1cKcsQMikHSUrPAwuwwGHDgnAkie8TTYPIgPCx51L+jak1D9NUBjraqME8PdK5GqUY9EZdc6R2vM2k7lZjzlHre3BHKFqJ7aD1eI1LFxg1NjjB+BoKxHDMyOvNerGcOp7i03tWc16V2sLQxShUE3hlVAC5aHfYN7jmNICwGUs2bFOBCiPx7u6Lut3z8UMMvfBNunHrtjfF9FjwUL72nsNa6OKqGmQv7gCLwOaY41Yq6HcXdwEU3P98jtnj0T4sqim1FB/aQTNRmjE0/v//VDkJNCvYlaRgmsLnRdjkFjJR1BMJxFlFMzsVNu52Jp2ATzqXZ+ks7U9dc211mU7nvbefoMxDK+C/enMgi5quXaHwVATPoyHWcCIsNCX62wnQmNy99Q3BvZFtuaYu073Q0JwathZhechqD5zmP9E55IIt/d8iCO6UYOu6l9vNguy3xnN6BbMw7cxxLswIk337M6/G533xi2+7+3bMuUhLI33QOmHcBj18fx4g6fI1YKCG/+n378xYCSNO40LrhyOQXprOsigRJyLHXa8czt6JGWQompnT+iJWZ5Jmh0uIMDP6UcDuI5EHedrFn45BxqPjNnmKoA9FvwkcUZvDwA+caXVgpfEmN7pHIw=
    DOCKER_USER:
      secure: VSaBUs5uQ7jdG8hlYRrM9XHQ80NYPlJP6zt0nbF7GlvpnqrULZK0CTGVqu63iRbG4kwsdGJpgtPC5jIV+X8SWn2NC/yVaris6lmGOXEEmeOjfHO2KH+E5UlDy+4URDUw472/dDEkFfuP8PaCZlRkrVqeS3WOfFvW87nkz59vYbybuJkdPlomwLf1S5bxU2kYBGntwsawPZkmKX4qIaIZPNcjBMYB75Wx7xno67haSNK3JwFXqgAd4LXOh31/21+E6VjofPBy5hB/wfh6tFNEaY5VdCWYiJ1g4punecwXhNb7qoyUy+D8ED5e5rWUarM86WVhuveye/zlfOxSYPvAcqWN5ve/dl+9afQhKyCkrDj4d2IesQeib6jFXh5KPFylUU0R4MUZ8pjzPwrSjRza86wbGpEuAfOmeZnoTydENEU9J5v8AQW91T+0pgi3Yx8Jp1eslj2Occ6LjItUSFERYVV/UIOPqsY6ZcN4W6kG5RBYqWhUSl8yjjjQAoxZWZ3ipgvLmgAYReiRkNL5F8FBSTk0pgQ7TPptdrb2Wx7SOvZ0m34IQAxRlEBT81j1vzD5zJZlXN3joVZqDl4rMsEKfLq7HzXJn9QmyW0PJ96cLI18epxi5p5j3/4hXUBk3/BBbWNU22f8b1/KXxpClMmCEoMEAAjSiDy6g5Gm/Ab5CFQ=
    DOCKER_PASS:
      secure: VSCZSMTIQj9Lux8xLrjzP/IYaYuxHDoW5gr+bznQi2yZLwNi1mYb2fQ7IFEWFJ1IS6CXclz2b2KxuXPL/RlNYgTJ104dOo+ifLkmL0jeM9fbAstlAsAbR3I0YkegLAf1GAPoPIb+ukWHt6n0eSIkWIZEhXWhU+mRuTOprF2j9ClfEPaSotJ/ToVwAgC4desUX5kHwXcIX6TcMx9GwvAkWAzGC21OQFE5ZETP294dpnIMAzZPFte8toE4INjs0uX1XDi0rX0CI16UM1MgDced+VQuhXRv/R8pAAzx7iozQ1mgBfTKeJ4B/kwxhauKfw2hAPU5p/Na4u7WZ/gqrYKxPW408OASwj6+w9Hg4IHs2hGxW0QobVx/gBFm6u3vPRgr0I/LqCEqGEO74+h8OeRie56vZBgbUOSlkxahqViGsK51beuElsDiUhJWZva3QlSgpuGcR1oWHX57/VfMWW311aam+YRsTFZA08A3BI9npvcZ7M8TlQ3YBQ9CCY0B8PYZ3EY9nhcb1QRon2u0RjPCFcm40lBYp/Xvc+lZ706fXzH+nH2IBjNS0THZuQblOs0ER5sjzM+LMM9BJ4rcJE7OVHj2+qv5vyu1y+ME3SvAWvPHNn0TSyqQdGVfZiVcWXdzZvbaRJm5QDqFUajWJfEfrqRqxrOisyynJZEUK+7M94I=
branches:
  only:
  - master
services:
- docker
before_script: 
script:
- bash ./unifi/mock_test.sh
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=$DOCKER_USER/ubiquiti-docker
- make -C unifi build
- if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then make -C unifi release; fi
after_success: 
