language: bash
sudo: required
env:
  global:
    DOCKER_USERNAME:
      secure: dookWegptxTZJkDfECp1OKovCCYw+SkNUXDE8cuiK1g4SZkQ3tw+6LH6VX81XECj7QJ9nux9MGd/IHTv1D8z7Zl/pF6hAlTaZ3ufUKagooW6B9q/euAOztTxQpk3JW+/doIwYPVQKHqiP77YY1VeuA2GB+40XkBzC+Lzvxpy68SNBjylMmtEPavlDi+vjpnbilW5YJZgFfutRrQNWoXNLk0IcnLFjInWvJFwSODeVYxAAL19Byf4bXy2TtVM5lwSHPV1swrvepTy8SxLCQlp3jG7abP6FGhkTZIwTNEvLhWE9fZvigVBtbBui1YU4TCTVJtAVtA29t9aVwv9+lxY9ylNdSEWcmpd7IODvUIayZnSGdsTqdbXkOg8vwczVmI8NDUePE/4V0tcNmBtjUkZ3Rke+TWaoOCNL9rFaIS4LPLQKMKJSYDzMjVub5M2zOBze3zOLBsGrrqkP2RVMjpGYTBlEIIlwK57iuDMvk8ErhCIFf4vabr+sN7Wgit1e0eDlT9kWeAHKUXFNQchiYoRzfxFjTxpvq4crPUe0hfi7dS/YZFyr6SpZJL2IpfYrIsdMxinbe183wdshjHen6pcMG1PLkYckfKOOLNlhECGJK4tSlPJySgLjocL7Sl4AX+7yLio+pFx4omQRQxYs+nTlHpbpc0Holp3SThkEcjr1IQ=
    DOCKER_PASS:
      secure: QgatQOpuvMjbPtF3k3XHr6hsAifmYNFKLpF+JzTx4O7BXQlu1+aELh+oOJH+STyBCNPiPqC9r0n/zzYhz4FxpvyuuLiLDlpN+0HsGLyRDpcxjqJMY0ph9lsOPMx4sKqx9eGfcXpPAfMy+gfLpZ6CnmykxLg1YwJysuTEa64VDzJ4Pvd08LiKLytOb3xPdmKeL0qghWneTX/hTwrHB92jbCPQKAhkF+m4+ZsAyct2v8P2ovcXgxB6snytCf7tHlcAL7HqmVLjVZm7a0c8DbQAFJBHaqC2GKqbAWwR4okS2rwhrpMaT6+oU7OJ3MgiUAeHgOjelgEWzqBB0lLZQ5Yo8RGwQXIrkULQNwVXSFdYP8nSWGLk+iDfw955ElKbYUfPfC0z2SKr4Oc5xlKNw3yNv21nbk1MSrF+R/6u4j8am+g/2WAeGUOWYwocx1bPNK7FR38aICxIbs0fjum2LBUU6s539IgTnic67PBub10FRN6IG3FwzyV/q0JuhM+TmbtJGBVaXxbzUkV0+0Oy0SxQgTv77g3wHu39pj5YdcW+ivGYmht1D2+Q7/TpOe1SS8FrnQ5GZLijz9zZD7KjSTMQaojZbZQIgt8B7YY/UeNEqzculAu4TTNHHWKhk+Q6oY0mnwGG7Ccx38cwWINzr8R3Ur3haS2bnnVDfszD6eM4q1k=
branches:
  only:
  - master
services:
- docker
before_script: 
script:
- bash ./unifi/mock_test.sh
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASS
- export REPO=$DOCKER_USER/ubiquiti-docker
- make -C unifi build
- if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then make -C unifi release; fi
after_success: 
