language: bash
sudo: required
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::6}

branches:
  only:
  - master

services:
- docker

before_script: 

script:
  - bash ./unifi/mock_test.sh
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=$DOCKER_USER/ubiquiti-docker
  - export TAG=`if [ “$TRAVIS_BRANCH” == “master” ]; then echo “latest”; else echo $TRAVIS_BRANCH ; fi`
  - make -C unifi build
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then make -C unifi release; fi
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    echo "Master Built and shipped"
    fi
