language: bash
sudo: required
env:
  global:
    DOCKER_USERNAME:
      secure: dookWegptxTZJkDfECp1OKovCCYw+SkNUXDE8cuiK1g4SZkQ3tw+6LH6VX81XECj7QJ9nux9MGd/IHTv1D8z7Zl/pF6hAlTaZ3ufUKagooW6B9q/euAOztTxQpk3JW+/doIwYPVQKHqiP77YY1VeuA2GB+40XkBzC+Lzvxpy68SNBjylMmtEPavlDi+vjpnbilW5YJZgFfutRrQNWoXNLk0IcnLFjInWvJFwSODeVYxAAL19Byf4bXy2TtVM5lwSHPV1swrvepTy8SxLCQlp3jG7abP6FGhkTZIwTNEvLhWE9fZvigVBtbBui1YU4TCTVJtAVtA29t9aVwv9+lxY9ylNdSEWcmpd7IODvUIayZnSGdsTqdbXkOg8vwczVmI8NDUePE/4V0tcNmBtjUkZ3Rke+TWaoOCNL9rFaIS4LPLQKMKJSYDzMjVub5M2zOBze3zOLBsGrrqkP2RVMjpGYTBlEIIlwK57iuDMvk8ErhCIFf4vabr+sN7Wgit1e0eDlT9kWeAHKUXFNQchiYoRzfxFjTxpvq4crPUe0hfi7dS/YZFyr6SpZJL2IpfYrIsdMxinbe183wdshjHen6pcMG1PLkYckfKOOLNlhECGJK4tSlPJySgLjocL7Sl4AX+7yLio+pFx4omQRQxYs+nTlHpbpc0Holp3SThkEcjr1IQ=
    DOCKER_PASSWORD:
      secure: VJHht5TvqS1G4vSAjcSR6+V4aYOtA+6smm6hBVa7ZV9/5Rc7C9yyV9MHPCW8LLn3nKbG5WCp3Rgu2s3EskCNsW3PxFkdtky9dDmq2+AXCq8gT5En0bLxrPShYS8uEJ9DNC4KiPG+RLP7yCiyAJHHr8mVna2DOQuh0NU3W1ImKvFEa7J6G7/C8rTYeeYEBusT42Su6/aPh9llvIdz+v3wRzOOLDAvIMlQ76b2FSJs6zmntQIszSn0nlId6OEMvfCSS2UpnZzRPYYpe48vT3wgm/IYZwEwrhe0fw1TtLdIBcDDjOsltKpUBl8xzQwoeVXKyEGDsDpe++vtkux2JcN1ZfNjf83XVx7TQ156F635zQ0Y4yxIuhX33PzT2ixZ52Gp6wMkQ61NmfthU1acL1vbpTp+M6jSAgjItYSlQLd5rdI3nkuS6Cy+/Z0W5r+JEoZbwdv7B8w3Nxlz3rdFtVLD3wrA4FzAxBxKfvUpdKMi7TzuaYhg8Ki1oq+AZcyY38B2wsb23C4q055NLwosyA7Sivs94OqMXCmG4Tx5MIkCxDlQsNmzftX5+VRkgLr+tBE8lLmEWQx2j3Y8lGjk+k3CgFjb9xUsGDiuAMX386O0t0lFLfA5joMQWnMXp9a+HA2ZmcjCn2HNaYBRp1N/9xtjhDOjROlsVE2p8t2xe25iiWc=
branches:
  only:
  - master
services:
- docker
before_script: 
script:
- bash ./unifi/mock_test.sh
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- export REPO=$DOCKER_USER/ubiquiti-docker
- make -C unifi build
- if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then make -C unifi release; fi
after_success: 
